-- Add additional districts

INSERT OR IGNORE INTO "DistrictModifiers"
	(	"DistrictType",					"ModifierId"							)
VALUES
-- Add Diplomatic Quarter, the Preserve really shouldn't have roads like that
-- Leugi's Garden also doesn't get roads
	(	'DISTRICT_DIPLOMATIC_QUARTER',	'JNR_VIA_DISTRICT_ROADS_ANCIENT_GOV'	),
	(	'DISTRICT_DIPLOMATIC_QUARTER',	'JNR_VIA_DISTRICT_ROADS_CLASSICAL_GOV'	),
	(	'DISTRICT_DIPLOMATIC_QUARTER',	'JNR_VIA_DISTRICT_ROADS_INDUSTRIAL'		),
	(	'DISTRICT_DIPLOMATIC_QUARTER',	'JNR_VIA_DISTRICT_ROADS_MODERN'			),
-- Support for City Lights; Just the boroughs, not the rurals
	(	'DISTRICT_COREEXPANSIONA',		'JNR_VIA_DISTRICT_ROADS_CLASSICAL'		),
	(	'DISTRICT_COREEXPANSIONA',		'JNR_VIA_DISTRICT_ROADS_INDUSTRIAL'		),
	(	'DISTRICT_COREEXPANSIONA',		'JNR_VIA_DISTRICT_ROADS_MODERN'			),
	(	'DISTRICT_COREEXPANSIONB',		'JNR_VIA_DISTRICT_ROADS_CLASSICAL'		),
	(	'DISTRICT_COREEXPANSIONB',		'JNR_VIA_DISTRICT_ROADS_INDUSTRIAL'		),
	(	'DISTRICT_COREEXPANSIONB',		'JNR_VIA_DISTRICT_ROADS_MODERN'			),
	(	'DISTRICT_COREEXPANSIONC',		'JNR_VIA_DISTRICT_ROADS_CLASSICAL'		),
	(	'DISTRICT_COREEXPANSIONC',		'JNR_VIA_DISTRICT_ROADS_INDUSTRIAL'		),
	(	'DISTRICT_COREEXPANSIONC',		'JNR_VIA_DISTRICT_ROADS_MODERN'			),
	(	'DISTRICT_COREX_FUERTE',		'JNR_VIA_DISTRICT_ROADS_CLASSICAL'		),
	(	'DISTRICT_COREX_FUERTE',		'JNR_VIA_DISTRICT_ROADS_INDUSTRIAL'		),
	(	'DISTRICT_COREX_FUERTE',		'JNR_VIA_DISTRICT_ROADS_MODERN'			),
-- Support for More Maritime Seaside Sectors; Just the Arsenal, the Waterfront matches the Preserve / Garden
	(	'DISTRICT_ARSENAL',				'JNR_VIA_DISTRICT_ROADS_CLASSICAL'		),
	(	'DISTRICT_ARSENAL',				'JNR_VIA_DISTRICT_ROADS_INDUSTRIAL'		),
	(	'DISTRICT_ARSENAL',				'JNR_VIA_DISTRICT_ROADS_MODERN'			);

INSERT OR IGNORE INTO "DistrictModifiers"
	(	"DistrictType",				"ModifierId"						)
SELECT	"CivUniqueDistrictType",	'JNR_VIA_DISTRICT_ROADS_CLASSICAL'
FROM	"DistrictReplaces"
WHERE	"ReplacesDistrictType" IN ('DISTRICT_COREEXPANSIONA', 'DISTRICT_COREEXPANSIONB', 'DISTRICT_COREEXPANSIONC', 'DISTRICT_COREX_FUERTE', 'DISTRICT_ARSENAL');

INSERT OR IGNORE INTO "DistrictModifiers"
	(	"DistrictType",				"ModifierId"						)
SELECT	"CivUniqueDistrictType",	'JNR_VIA_DISTRICT_ROADS_INDUSTRIAL'
FROM	"DistrictReplaces"
WHERE	"ReplacesDistrictType" IN ('DISTRICT_COREEXPANSIONA', 'DISTRICT_COREEXPANSIONB', 'DISTRICT_COREEXPANSIONC', 'DISTRICT_COREX_FUERTE', 'DISTRICT_ARSENAL');

INSERT OR IGNORE INTO "DistrictModifiers"
	(	"DistrictType",				"ModifierId"						)
SELECT	"CivUniqueDistrictType",	'JNR_VIA_DISTRICT_ROADS_MODERN'
FROM	"DistrictReplaces"
WHERE	"ReplacesDistrictType" IN ('DISTRICT_COREEXPANSIONA', 'DISTRICT_COREEXPANSIONB', 'DISTRICT_COREEXPANSIONC', 'DISTRICT_COREX_FUERTE', 'DISTRICT_ARSENAL');

INSERT OR IGNORE INTO "DistrictModifiers"
	(	"DistrictType",				"ModifierId"						)
SELECT	"CivUniqueDistrictType",	'JNR_VIA_DISTRICT_ROADS_ANCIENT_GOV'
FROM	"DistrictReplaces"
WHERE	"ReplacesDistrictType" IN ('DISTRICT_DIPLOMATIC_QUARTER');

INSERT OR IGNORE INTO "DistrictModifiers"
	(	"DistrictType",				"ModifierId"						)
SELECT	"CivUniqueDistrictType",	'JNR_VIA_DISTRICT_ROADS_CLASSICAL_GOV'
FROM	"DistrictReplaces"
WHERE	"ReplacesDistrictType" IN ('DISTRICT_DIPLOMATIC_QUARTER');
